# -*- mode: org; -*-
#+TITLE: README
#+AUTHOR: Colin Baxter
#+EMAIL:
#+DATE:
#+STARTUP: showeverything
#+LANGUAGE:  en
# #+SEQ_TODO: To_do01 TO_DO02
# Uncomment above line to set a couple of todos

# -------- Begin File

* What is it?
A really simple color theme for emacs.

* Installation
The simplest way to install is to download the file
=simple-dark-theme.el= and put it in your custom theme directory. The
default value of the custom theme directory is =~/.emacs.d/themes=,
but you can change this by adding the lines

#+begin_src elisp
 (setq custom-theme-directory "~/path/to/personal/themes/directory")
#+end_src

to your emacs init file (usually =~/.emacs=). To load the theme, add
the lines

#+begin_src elisp
 (load-theme 'simple-dark t t)
 (enable-theme 'simple-dark)
#+end_src

to your emacs init file, or do =M-x load-theme= then press TAB to show
a list of available themes and then select appropriately. The process
can be reversed by doing =M-x disable-theme=.

If you have a =custom-set-faces= in your emacs-init file then you may
find the colors have change. If this is not what one what then either
delete or comment out the custom-set-faces.

* Modifications
A =simple-light-theme= can be created by just changing the line

#+begin_src elisp
 '(default ((t (:foreground "white" :background "black" :weight normal))))
#+end_src

in =simple-dark-theme.el= to

#+begin_src elisp
 '(default ((t (:foreground "black" :background "white" :weight normal))))
#+end_src

You can the use something like
https://github.com/valignatev/heaven-and-hell to toggle between simple
dark and simple light themes.

* End of file and local variables                                  :noexport:
# Local Variables:
# eval: (setq org-confirm-babel-evaluate nil)
# End:
